### ISSUE TITLE
ModuleNotFoundError, pip doesn't seem to install properly

### ISSUE THREAD

**Issue by d-tork** [jeffcsauer/arcospy#2]
After installing via pip, my python environment can't find the package. And when I try to install it manually, it has no commands associated with it. 

## Install with pip, beginning from a blank-slate environment
```bash
python3 -m venv venv
source venv/bin/activate
python -m pip install --upgrade pip arcospy
```
(nothing wrong yet)
```
>>> import arcospy
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'arcospy'
```
Afterward I noticed that there is no source code for `arcospy` in `venv/lib/python3.10/site-packages`, only the dist-info directory, so it makes sense that python can't import it.

## Install manually
```bash
git clone https://github.com/jeffcsauer/arcospy.git
cd arcospy
python -m pip install . pandas requests
```
This time it installs _and_ I can import it, but there is nothing available as a command (at least not like what's expected from the examples).
```
>>> import arcospy
>>> help(arcospy)
Help on package arcospy:

NAME
    arcospy

PACKAGE CONTENTS
    arcospy

FILE
    /tmp/arcostest/arcospy/arcospy/__init__.py
```

As it turns out while writing this issue, one of my computers reports 
```
AttributeError: module 'arcospy' has no attribute 'county_raw'
```
but another one (thankfully) proceeds with the command, even though I did the same manual install steps on both. It's a workaround I suppose, but what could be going wrong with the pip install?

**Comment by jeffcsauer** [comment]
Hey! Thanks so much for flagging this. Must be related to the most recent update I made. I will investigate in the coming weekend - if you have any ideas or want to open a PR, feel free to do so :)

**Comment by jeffcsauer** [comment]
Played around a bit and no avail. Plan is to revert repo to only update the URL and avoid all the little tweaks I made to clean things up. Will post when done.

**Comment by jeffcsauer** [comment]
Running into the same issue even after reverting repo. For the time being I am going to recommend users extract the functions they need while I source additional resources to address the issue. The updated functions are working with the new URL, so you may just need to extract those for the time being.

**Comment by jeffcsauer** [comment]
@d-tork Could you please try `pip install arcospy==1.3.5` and see if it resolves your issue?

**Comment by d-tork** [comment]
It works, yes! The help documentation in the REPL is still sparse, as in it doesn't list the functions with their parameters, but this is a small thing as I rarely call `help()` if I'm reading documentation for it online. I believe it's because the package isn't organized into modules and classes, but with what you have here that may be overkill anyway.
